### 开发环境


### 支持配置热更新

provider=reconfigurable
# 创建用于禁止JVM优化的日志writer，这样可以实现tinylog配置的热更新
writerBlackHole=black hole
# 此处设置的日志级别可以限定可输出的最低日志级别，针对该级别以下的日志级别的动态配置将无法生效，但可以享受JVM的优化
writerBlackHole.level=debug


### tinylog的正式配置

writerConsole=console
writerConsole.level=info
writerConsole.format={level} {date} [{thread}] {class}.{method}: {message}

# 输出日志文件
writerFile=rolling file
writerFile.level=info
writerFile.backups=4
writerFile.policies=startup,size: 5MB
writerFile.charset=UTF-8
writerFile.append=true
writerFile.format={level} {date} [{thread}] {class}.{method}: {message}